all:
  children:
    coturn:
      hosts:
        10.32.4.205:
          ansible_host: 127.0.0.1
          ansible_port: 10022
          ansible_user: ubuntu
          turn_credential: "{{ turn_credential }}"
          turn_realm: pcdx.jp
        10.32.5.142:
          ansible_host: 127.0.0.1
          ansible_port: 10022
          ansible_user: ubuntu
          turn_credential: "{{ turn_credential }}"
          turn_realm: pcdx.jp
