name: Ansible Windows Test

on:
  push:
  pull_request:

jobs:
  ansible:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core<2.16" pywinrm

      - name: Run Ansible (force UTF-8)
        shell: pwsh
        run: |
          chcp 65001
          $env:PYTHONUTF8 = "1"
          $env:PYTHONIOENCODING = "utf-8"
          $env:LANG = "C.UTF-8"
          $env:LC_ALL = "C.UTF-8
